on:
  push:
    branches: ["*"]
    types: [opened, synchronize, reopened]
  pull_request:
    branches: [ "*" ]
    types: [opened, synchronize, reopened]

permissions: write-all

jobs:
  openai-code-review:
    runs-on: ubuntu-latest
    name: OpenAI code review
    steps:
      - name: Golang setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5

      - name: Checkout
        uses: actions/checkout@v3

      # - name: OpenAI code review
        